### ISSUE TITLE
Something wrong or mixed up? 

### ISSUE THREAD

**Issue by YilunZhou** [mlresearch/v155#1]
It looks like something is wrong with this repo. The papers are from CoRL 2020, but it is listed as proceedings of CoRL 2021 on the home page https://proceedings.mlr.press/ . Also, it seems to come out so late (CoRL 2021 is happening right now), and it gets assigned to Volume 155, while most of the volumes around it are for conferences of their 2021 version. Last, only a handful of papers are uploaded and the repo has been quite for a month https://github.com/mlresearch/v155 . Is it actually supposed to be CoRL 2020 or 2021 proceeding? There seems to be some logisic and administrative issues that need to be sorted out.

**Comment by lawrennd** [comment]
Great spot, thank you Yilun, I must have got confused when receiving the proceedings. I've updated the main heading.

One confusing bit is that the year of publication is when the proceedings go up (not when the conferences happen). I try and encourage conferences to prepublish, but I appreciate that's not something that everyone can always accommodate.
